_doc: Eval config template
name: prototype
eval_sample_count: null
eval_sample_seed: 42
gen_eval_model: gpt2-large
gen_eval_model_dtype: bf16
gen_eval_model_device: cuda
use_fast_infer: false
eval_gen_steps: 128
