_doc: arXiv abstracts dataset config

name: arxiv
repo_id: gfissore/arxiv-abstracts-2021
revision: main
download_split: train
download_path: cache/datasets/arxiv
split: train | eval
eval_count: 10000
eval_seed: 42
